version: '2'
services:
  chinachu:
    build:
        context: chinachu
        args:
         - REPOSITORY=git://github.com/Chinachu/Chinachu.git
         - BRANCH=gamma
    container_name: chinachu
    ports:
     - "10772:10772"
     - "20772:20772"
     - "5353:5353/udp"
    environment:
     - "TZ=JST-9"
    volumes:
     - ./chinachu/conf/config.json:/usr/local/chinachu/config.json
     - ./chinachu/conf/rules.json:/usr/local/chinachu/rules.json
     - ./chinachu/data:/usr/local/chinachu/data
     - ./recorded:/usr/local/chinachu/recorded
    extra_hosts:
     - "container-mirakurun:192.168.0.2" # Please fix for your environment!
